name: innofast_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.2
  http: ^1.3.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  fluttertoast: ^8.2.12
  carousel_slider: ^5.0.0
  shimmer_animation:
  dropdown_button2: ^2.3.9
  flutter_svg:
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.0.0
  path_provider: ^2.1.5
  flutter_widget_from_html: ^0.16.0
  intl:
  font_awesome_flutter: ^10.8.0
  connectivity_plus: ^6.1.4
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.1
  flutter_inappwebview: ^6.1.5
  country_code_picker: ^3.3.0
  phone_numbers_parser: ^9.0.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900